image: rocker/tidyverse

stages:
  - build
  - test
  - deploy

building:
  stage: build
  script:
    # explicitly install Bioconductor dependencies
    - R -e "remotes::install_bioc('GenomicRanges')"
    - R -e "remotes::install_deps(dependencies = TRUE)"
    - R -e 'devtools::check()'

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
    stage: test
    allow_failure: true
    when: on_success
    only:
        - master
    script:
        # explicitly install Bioconductor dependencies
        - Rscript -e "remotes::install_bioc('GenomicRanges')"
        - Rscript -e 'install.packages("DT")'
        - Rscript -e 'install.packages("RcppGreedySetCover")'
        - Rscript -e 'devtools::install()'
        - Rscript -e 'covr::gitlab(quiet = FALSE)'
    artifacts:
        paths:
            - public

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

pages:
    stage: deploy
    dependencies:
        - testing
    script:
        - ls
        - Rscript -e "remotes::install_bioc('GenomicRanges')"
        - Rscript -e 'install.packages("DT")'
        - Rscript -e 'install.packages("RcppGreedySetCover")'
        - Rscript -e 'devtools::install()'
        - Rscript -e 'install.packages("pkgdown")'
        - Rscript -e "pkgdown::build_site()"
        - cp -r docs/* public
    artifacts:
        paths:
            - public
        expire_in: 120 days
    only:
        - master
